config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

end

app/models/device.rb
class Device < ActiveRecord::Base
	has_many :users
	default_scope { order('id DESC') }

	def name=(value)
    raise ArgumentError unless value.is_a?(String)
    raise ArgumentError unless value.length >= 4
    raise ArgumentError unless value.length <= 16
    super
	end

def address=(value)
    #^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$
    raise ArgumentError unless value.is_a?(String)
    raise ArgumentError unless /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/ =~ value
    super
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :devices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/edit.html.erb
<h1>Devices#edit</h1>
<p>Find me in app/views/devices/edit.html.erb</p>

app/views/devices/index.html.erb
<h1>Devices#index</h1>
<p>Find me in app/views/devices/index.html.erb</p>

app/views/devices/new.html.erb
<h1>Devices#new</h1>
<p>Find me in app/views/devices/new.html.erb</p>

app/views/devices/show.html.erb
<h1>Devices#show</h1>
<p>Find me in app/views/devices/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>